Added homework extension, exercise: 3,4,5 and part-y 1
KulkovN/geekshop-project pull request #3
Opened 2021-05-31 20:27 UTC by KulkovN

2021-05-31 20:28 UTC, KulkovN commented
По состоянию на 31.05.21 -  выложен не конечный результат дз

2021-06-01 17:10 UTC, KulkovN commented
Сделал все, за исключением вывода картинок в карточке товара (закоментированы строки 63-64 в products.html)
При отрисовке, картинки вываливаются за границы блока, как это можно поправить?

2021-06-01 18:21 UTC, Vokler requested changes

2021-06-01 18:21 UTC, Vokler commented on products/views.py
> +             'image': "/vendor/img/products/Adidas-hoodie.png"},
Попробуйте везде убрать первый слэш `/`, то есть сделать `vendor/img/products/Adidas-hoodie.png`.

2021-06-01 19:35 UTC, KulkovN commented on products/views.py
> +             'image': "/vendor/img/products/Adidas-hoodie.png"},
не помогло..

2021-06-01 20:27 UTC, KulkovN commented
Удалось локализовать и решить проблему
Поехала верстка, не верно переписал класс-ссылку CSS (см. строки 63,64)

2021-06-02 07:59 UTC, Vokler approved these changes

2021-06-02 07:59 UTC, merged